# Generated by Django 5.0.1 on 2024-03-04 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0003_alter_diagnosis_diagnosis_name_alter_ward_ward_name'),
        ('PharmacistApp', '0001_initial'),
        ('ReceptionApp', '0005_remove_waitinglist_blood_pressure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_reason', models.CharField(max_length=300)),
                ('admitted_ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorApp.ward')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_conplaint', models.CharField(max_length=500)),
                ('secondary_conplaint', models.CharField(max_length=200, null=True)),
                ('physical_findings', models.CharField(max_length=500)),
                ('test_results', models.CharField(max_length=200, null=True)),
                ('diagnosed_datetime', models.DateTimeField(auto_now_add=True)),
                ('diagnosedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('primary_diagnosis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_diagnosis_details', to='DoctorApp.diagnosis')),
                ('secondary_diagnosis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_diagnosis_details', to='DoctorApp.diagnosis')),
                ('waitingList', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ReceptionApp.waitinglist')),
            ],
        ),
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('instruction', models.CharField(max_length=200)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PharmacistApp.medicine')),
                ('relatedDiagDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorApp.diagnosisdetails')),
            ],
        ),
    ]
