# Generated by Django 5.0.1 on 2024-03-11 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0004_admission_diagnosisdetails_prescribedmedicine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescribedmedicine',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='diagnosisdetails',
            name='is_prescription_denied',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisdetails',
            name='prescription_approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvepharmacist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diagnosisdetails',
            name='diagnosedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosisdoctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
