# Generated by Django 4.2.7 on 2024-03-12 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0005_remove_prescribedmedicine_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='related_diag_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DoctorApp.diagnosisdetails'),
            preserve_default=False,
        ),
    ]
