# Generated by Django 5.0.1 on 2024-03-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0006_admission_related_diag_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='is_discharged',
            field=models.BooleanField(default=False),
        ),
    ]
