# Generated by Django 5.0.1 on 2024-02-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReceptionApp', '0002_patient_guardian_name_patient_relationship'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waitinglist',
            unique_together={('patient', 'consult_date')},
        ),
    ]
