# Generated by Django 4.2.7 on 2024-02-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceptionApp', '0003_alter_waitinglist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='isReady',
            field=models.BooleanField(default=False),
        ),
    ]
