# Generated by Django 4.2.7 on 2024-03-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceptionApp', '0005_remove_waitinglist_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='idDiagnosed',
            field=models.BooleanField(default=False),
        ),
    ]
