# Generated by Django 4.2.7 on 2024-03-12 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReceptionApp', '0006_waitinglist_iddiagnosed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitinglist',
            old_name='idDiagnosed',
            new_name='isDiagnosed',
        ),
    ]
