# Generated by Django 5.0.1 on 2024-04-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceptionApp', '0007_rename_iddiagnosed_waitinglist_isdiagnosed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='NRCnum',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
